// Cloud build (Vercel + Supabase) — renderer-only Vite build. No Electron
// main/preload, no PC server: the bundle is a static SPA that talks to
// Supabase (auth/projects/settings/edge functions) and does all media work
// on-device. `npm run build:cloud` -> dist-cloud/ (what Vercel serves).
import { resolve } from 'path'
import { defineConfig, loadEnv, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'

/** The index.html CSP is written for Electron/self-host (same-origin only) —
 *  it blocks fetch() to *.supabase.co ("Failed to fetch" on login) and wasm
 *  compilation (in-browser Silero VAD). Rewrite it for the cloud origin:
 *  connect to the Supabase project, allow WebAssembly, allow blob: workers. */
function cloudCsp(supabaseUrl: string | undefined): Plugin {
  let origin = ''
  try {
    origin = new URL(supabaseUrl ?? '').origin
  } catch {
    /* unset locally — fall back to any supabase project */
  }
  const https = origin || 'https://*.supabase.co'
  const wss = https.replace(/^https/, 'wss')
  const CSP = [
    "default-src 'self'",
    `connect-src 'self' blob: data: ${https} ${wss}`,
    "img-src 'self' data: blob:",
    "media-src 'self' blob: data:",
    "style-src 'self' 'unsafe-inline'",
    // wasm-unsafe-eval: onnxruntime-web (Silero VAD) compiles wasm at runtime
    "script-src 'self' 'wasm-unsafe-eval'",
    // ort spawns blob: workers for its wasm proxy/threads
    "worker-src 'self' blob:"
  ].join('; ')
  return {
    name: 'cloud-csp',
    transformIndexHtml(html) {
      return html.replace(
        /(http-equiv="Content-Security-Policy"[\s\S]*?content=")[^"]*(")/,
        `$1${CSP}$2`
      )
    }
  }
}

export default defineConfig(({ mode }) => {
  // '' prefix = also surface non-VITE process.env (Vercel sets real env vars).
  const env = loadEnv(mode, __dirname, '')
  return {
    root: resolve(__dirname, 'src/renderer'),
    // VITE_SUPABASE_* come from .env files here (or real env vars on Vercel).
    envDir: __dirname,
    // Generated by scripts/prepare-cloud-assets.mjs: /vad/ (Silero ONNX + ORT wasm).
    publicDir: resolve(__dirname, '.cloud-public'),
    define: {
      // Hard-bake the cloud flag — IS_CLOUD gates compile away in other builds.
      'import.meta.env.VITE_CLOUD': JSON.stringify('1'),
      // Premium redesign is LIVE on the cloud build by default. Still overridable:
      // set VITE_NEW_EASECUT_UI=false in the Vercel env (+ redeploy) to fall back
      // to the legacy UI. The Electron/self-host builds are unaffected and stay on
      // the legacy UI unless the var is explicitly 'true'.
      'import.meta.env.VITE_NEW_EASECUT_UI': JSON.stringify(env.VITE_NEW_EASECUT_UI ?? 'true')
    },
    build: {
      outDir: resolve(__dirname, 'dist-cloud'),
      emptyOutDir: true,
      // Emit source maps so a minified on-device stack (mobile Safari) can be
      // decoded back to the real source line while we stabilize the iOS path.
      sourcemap: true,
      rollupOptions: {
        input: { index: resolve(__dirname, 'src/renderer/index.html') }
      }
    },
    resolve: {
      alias: {
        '@renderer': resolve(__dirname, 'src/renderer/src'),
        '@shared': resolve(__dirname, 'src/shared')
      }
    },
    plugins: [react(), cloudCsp(env.VITE_SUPABASE_URL)]
  }
})
