// Cloud build (Vercel + Supabase) — renderer-only Vite build. No Electron
// main/preload, no PC server: the bundle is a static SPA that talks to
// Supabase (auth/projects/settings/edge functions) and does all media work
// on-device. `npm run build:cloud` -> dist-cloud/ (what Vercel serves).
import { resolve } from 'path'
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  root: resolve(__dirname, 'src/renderer'),
  // VITE_SUPABASE_* come from .env files here (or real env vars on Vercel).
  envDir: __dirname,
  // Generated by scripts/prepare-cloud-assets.mjs: /vad/ (Silero ONNX + ORT wasm).
  publicDir: resolve(__dirname, '.cloud-public'),
  define: {
    // Hard-bake the cloud flag — IS_CLOUD gates compile away in other builds.
    'import.meta.env.VITE_CLOUD': JSON.stringify('1')
  },
  build: {
    outDir: resolve(__dirname, 'dist-cloud'),
    emptyOutDir: true,
    rollupOptions: {
      input: { index: resolve(__dirname, 'src/renderer/index.html') }
    }
  },
  resolve: {
    alias: {
      '@renderer': resolve(__dirname, 'src/renderer/src'),
      '@shared': resolve(__dirname, 'src/shared')
    }
  },
  plugins: [react()]
})
