// Cloud build (Vercel + Supabase) — renderer-only Vite build. No Electron
// main/preload, no PC server: the bundle is a static SPA that talks to
// Supabase (auth/projects/settings/edge functions) and does all media work
// on-device. `npm run build:cloud` -> dist-cloud/ (what Vercel serves).
import { resolve } from 'path'
import { defineConfig, loadEnv, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'

/** The index.html CSP is written for Electron/self-host (same-origin only) —
 *  it blocks fetch() to *.supabase.co ("Failed to fetch" on login) and wasm
 *  compilation (in-browser Silero VAD). Rewrite it for the cloud origin:
 *  connect to the Supabase project, allow WebAssembly, allow blob: workers. */
function cloudCsp(supabaseUrl: string | undefined): Plugin {
  let origin = ''
  try {
    origin = new URL(supabaseUrl ?? '').origin
  } catch {
    /* unset locally — fall back to any supabase project */
  }
  const https = origin || 'https://*.supabase.co'
  const wss = https.replace(/^https/, 'wss')
  const CSP = [
    "default-src 'self'",
    // *.paddle.com: Paddle.js posts to Paddle's checkout services.
    `connect-src 'self' blob: data: ${https} ${wss} https://*.paddle.com`,
    "img-src 'self' data: blob: https://*.paddle.com",
    "media-src 'self' blob: data:",
    // fonts.googleapis: landing webfont stylesheet. font-src: the font files.
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
    "font-src 'self' https://fonts.gstatic.com",
    // wasm-unsafe-eval: onnxruntime-web (Silero VAD) compiles wasm at runtime.
    // *.paddle.com: Paddle.js is served from cdn.paddle.com.
    "script-src 'self' 'wasm-unsafe-eval' https://*.paddle.com",
    // ort spawns blob: workers for its wasm proxy/threads
    "worker-src 'self' blob:",
    // Paddle renders its hosted checkout in an iframe ((sandbox-)buy.paddle.com)
    "frame-src https://*.paddle.com"
  ].join('; ')
  return {
    name: 'cloud-csp',
    transformIndexHtml(html) {
      return html.replace(
        /(http-equiv="Content-Security-Policy"[\s\S]*?content=")[^"]*(")/,
        `$1${CSP}$2`
      )
    }
  }
}

export default defineConfig(({ mode }) => {
  // '' prefix = also surface non-VITE process.env (Vercel sets real env vars).
  const env = loadEnv(mode, __dirname, '')
  return {
    root: resolve(__dirname, 'src/renderer'),
    // VITE_SUPABASE_* come from .env files here (or real env vars on Vercel).
    envDir: __dirname,
    // Dev parity for the production /edge rewrite (vercel.json): the app calls
    // edge functions same-origin (ad-blocker-proof); proxy them to the Supabase
    // functions host in `dev:cloud` too. Without the env var the app's built-in
    // fallback (direct supabase-js call) still keeps everything working.
    server: env.VITE_SUPABASE_URL
      ? {
          proxy: {
            '/edge': {
              target: `${env.VITE_SUPABASE_URL.replace(/\/$/, '')}/functions/v1`,
              changeOrigin: true,
              rewrite: (p: string) => p.replace(/^\/edge/, '')
            }
          }
        }
      : undefined,
    // Generated by scripts/prepare-cloud-assets.mjs: /vad/ (Silero ONNX + ORT wasm)
    // and /ffmpeg/ (ffmpeg.wasm core — the on-device audio decoder of last resort).
    publicDir: resolve(__dirname, '.cloud-public'),
    // @ffmpeg/ffmpeg spawns its worker via `new Worker(new URL('./worker.js',
    // import.meta.url))`; esbuild dep pre-bundling rewrites import.meta.url and
    // breaks that, so let Rollup/Vite's worker plugin process it from source.
    optimizeDeps: { exclude: ['@ffmpeg/ffmpeg', '@ffmpeg/util'] },
    define: {
      // Hard-bake the cloud flag — IS_CLOUD gates compile away in other builds.
      'import.meta.env.VITE_CLOUD': JSON.stringify('1')
    },
    build: {
      outDir: resolve(__dirname, 'dist-cloud'),
      emptyOutDir: true,
      // Emit source maps so a minified on-device stack (mobile Safari) can be
      // decoded back to the real source line while we stabilize the iOS path.
      sourcemap: true,
      rollupOptions: {
        input: { index: resolve(__dirname, 'src/renderer/index.html') }
      }
    },
    resolve: {
      alias: {
        '@renderer': resolve(__dirname, 'src/renderer/src'),
        '@shared': resolve(__dirname, 'src/shared')
      }
    },
    plugins: [react(), cloudCsp(env.VITE_SUPABASE_URL)]
  }
})
