name: easecut
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.13+14

environment:
  sdk: ^3.12.2

dependencies:
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  supabase_flutter: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: InstrumentSans
      fonts:
        - asset: assets/fonts/InstrumentSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/InstrumentSans-Bold.ttf
          weight: 700
    - family: IBMPlexMono
      fonts:
        - asset: assets/fonts/IBMPlexMono-Regular.ttf
          weight: 400
        - asset: assets/fonts/IBMPlexMono-SemiBold.ttf
          weight: 600
